### ISSUE TITLE
Add create command

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisky#19]
A user should be able to use the create command to create:

- [x] account
- [x] transaction: transfer
- [x] transaction: register second passphrase
- [x] transaction: register delegate
- [x] transaction: cast votes
- [x] transaction: create multisignature group

Another idea is for accounts/wallets to have names, so you can log into a wallet and see which one you're using in the delimiter. Eg. `lisky:my-wallet@testnet>`.

Dapps will come later when the specification is better defined.
