### ISSUE TITLE
Apply lisk-template standards

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#426]
### Description

Not all of the Lisk standards are in place in Lisky. This is a parent issue; child issues will be populated and opened later.

### Todo

~~Update .nvmrc (#442)~~
~~Update .npmrc file (#443)~~
~~Update Jenkinsfiles to standards (#447)~~

- [x] Standardize .gitignore file (#444)
- [x] Standardize package.json field (#445)
- [x] Standardize npm scripts  (#446)
- [x] Update/Standardize package manager (#449)
- [x] Husky and lint-staged (#453)
- [x] Update/Standardize mocha/chai/sinon setup (e.g. sandbox) (#448 )
- [x] Be consistent about use of `should` vs `expect` (#450)
- [x] underscore_separated file/directory names (#312)
- [x] Update ESLint (#451)
- [x] README.md (#460)
